export const certificationsData = [
  {
    "id": 1,
    "name": "AWS Certified Solutions Architect - Associate",
    "provider": "Amazon Web Services",
    "category": "Cloud Computing",
    "level": "Associate",
    "duration": "3 years",
    "cost": 150,
    "image": "https://images.credly.com/size/340x340/images/0e284c3f-5164-4b21-8660-0d84737941bc/image.png",
    "description": "Validates technical expertise in designing distributed systems on AWS",
    "skills": ["AWS Architecture", "Security", "Compute", "Storage", "Networking"],
    "prerequisites": ["AWS Cloud Practitioner (recommended)", "1 year AWS hands-on experience"],
    "examCode": "SAA-C03",
    "popularity": 95,
    "averageSalary": 140000,
    "jobTitles": ["Solutions Architect", "Cloud Engineer", "DevOps Engineer"],
    "officialUrl": "https://aws.amazon.com/certification/certified-solutions-architect-associate/"
  },
  {
    "id": 2,
    "name": "Microsoft Azure Fundamentals",
    "provider": "Microsoft",
    "category": "Cloud Computing",
    "level": "Fundamental",
    "duration": "No expiration",
    "cost": 99,
    "image": "https://images.credly.com/size/340x340/images/be8fcaeb-c769-4858-b567-ffaaa73ce8cf/image.png",
    "description": "Foundational knowledge of cloud services and Microsoft Azure",
    "skills": ["Azure Services", "Cloud Concepts", "Security", "Compliance", "Trust"],
    "prerequisites": ["None"],
    "examCode": "AZ-900",
    "popularity": 90,
    "averageSalary": 75000,
    "jobTitles": ["Cloud Support", "Junior Cloud Engineer", "System Administrator"],
    "officialUrl": "https://learn.microsoft.com/en-us/certifications/azure-fundamentals/"
  },
  {
    "id": 3,
    "name": "Google Cloud Professional Cloud Architect",
    "provider": "Google Cloud",
    "category": "Cloud Computing",
    "level": "Professional",
    "duration": "2 years",
    "cost": 200,
    "image": "https://api.accredible.com/v1/frontend/credential_website_embed_image/badge/60816099",
    "description": "Design, develop, and manage scalable, secure cloud architecture",
    "skills": ["GCP Architecture", "Security", "Data Analysis", "Machine Learning", "Networking"],
    "prerequisites": ["3+ years industry experience", "1+ year GCP experience"],
    "examCode": "Professional Cloud Architect",
    "popularity": 80,
    "averageSalary": 150000,
    "jobTitles": ["Cloud Architect", "Senior Cloud Engineer", "Technical Lead"],
    "officialUrl": "https://cloud.google.com/certification/cloud-architect"
  },
  {
    "id": 4,
    "name": "Cisco Certified Network Associate (CCNA)",
    "provider": "Cisco",
    "category": "Networking",
    "level": "Associate",
    "duration": "3 years",
    "cost": 300,
    "image": "https://images.credly.com/size/340x340/images/683783d8-eaac-4c37-a14d-11bd8a36321d/ccna_600.png",
    "description": "Foundation skills for networking professionals",
    "skills": ["Network Fundamentals", "Network Access", "IP Connectivity", "IP Services", "Security Fundamentals"],
    "prerequisites": ["None"],
    "examCode": "200-301 CCNA",
    "popularity": 85,
    "averageSalary": 85000,
    "jobTitles": ["Network Engineer", "Network Administrator", "System Administrator"],
    "officialUrl": "https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/associate/ccna.html"
  },
  {
    "id": 5,
    "name": "Oracle Java SE 11 Developer",
    "provider": "Oracle",
    "category": "Programming",
    "level": "Professional",
    "duration": "No expiration",
    "cost": 245,
    "image": "https://brm-workforce.oracle.com/pdf/certview/images/OCPJSE11D.png",
    "description": "Professional-level Java SE 11 programming skills",
    "skills": ["Java Programming", "Object-Oriented Programming", "Collections", "Streams", "Concurrency"],
    "prerequisites": ["Java SE 8 Programmer I or equivalent experience"],
    "examCode": "1Z0-819",
    "popularity": 75,
    "averageSalary": 95000,
    "jobTitles": ["Java Developer", "Software Engineer", "Backend Developer"],
    "officialUrl": "https://education.oracle.com/java-se-11-developer/pexam_1Z0-819"
  },
  {
    "id": 6,
    "name": "AWS Certified Developer - Associate",
    "provider": "Amazon Web Services",
    "category": "Development",
    "level": "Associate",
    "duration": "3 years",
    "cost": 150,
    "image": "https://images.credly.com/size/340x340/images/b9feab85-1a43-4f6c-99a5-631b88d5461b/image.png",
    "description": "Develop and maintain applications on AWS",
    "skills": ["AWS SDK", "Serverless", "Security", "Deployment", "Troubleshooting"],
    "prerequisites": ["1+ year hands-on AWS experience"],
    "examCode": "DVA-C02",
    "popularity": 85,
    "averageSalary": 125000,
    "jobTitles": ["Cloud Developer", "DevOps Engineer", "Software Engineer"],
    "officialUrl": "https://aws.amazon.com/certification/certified-developer-associate/"
  },
  {
    "id": 7,
    "name": "Microsoft Azure Administrator Associate",
    "provider": "Microsoft",
    "category": "Cloud Administration",
    "level": "Associate",
    "duration": "No expiration",
    "cost": 165,
    "image": "https://images.credly.com/size/340x340/images/336eebfc-0ac3-4553-9a67-b402f491f185/azure-administrator-associate-600x600.png",
    "description": "Implement, manage, and monitor Azure environments",
    "skills": ["Azure Infrastructure", "Storage", "Virtual Networks", "Identity Management", "Governance"],
    "prerequisites": ["6+ months Azure administration experience"],
    "examCode": "AZ-104",
    "popularity": 88,
    "averageSalary": 100000,
    "jobTitles": ["Azure Administrator", "Cloud Administrator", "System Administrator"],
    "officialUrl": "https://learn.microsoft.com/en-us/certifications/azure-administrator/"
  },
  {
    "id": 8,
    "name": "CompTIA Security+",
    "provider": "CompTIA",
    "category": "Cybersecurity",
    "level": "Entry Level",
    "duration": "3 years",
    "cost": 370,
    "image": "https://images.credly.com/size/340x340/images/74790a75-8451-400a-8536-92d792b5184a/CompTIA_Security_2Bce.png",
    "description": "Core cybersecurity skills for IT professionals",
    "skills": ["Network Security", "Compliance", "Operational Security", "Threats", "Cryptography"],
    "prerequisites": ["Network+ and 2 years IT administration experience (recommended)"],
    "examCode": "SY0-601",
    "popularity": 92,
    "averageSalary": 87000,
    "jobTitles": ["Security Analyst", "Security Engineer", "IT Security Specialist"],
    "officialUrl": "https://www.comptia.org/certifications/security"
  },
  {
    "id": 9,
    "name": "Kubernetes Certified Administrator (CKA)",
    "provider": "Cloud Native Computing Foundation",
    "category": "Container Orchestration",
    "level": "Professional",
    "duration": "3 years",
    "cost": 375,
    "image": "https://images.credly.com/size/340x340/images/8b8ed108-e77d-4396-ac59-2504583b9d54/cka_from_cncfsite__281_29.png",
    "description": "Kubernetes administration skills and knowledge",
    "skills": ["Cluster Management", "Workloads", "Services", "Storage", "Troubleshooting"],
    "prerequisites": ["Container and Kubernetes experience"],
    "examCode": "CKA",
    "popularity": 78,
    "averageSalary": 130000,
    "jobTitles": ["Kubernetes Administrator", "DevOps Engineer", "Platform Engineer"],
    "officialUrl": "https://www.cncf.io/certification/cka/"
  },
  {
    "id": 10,
    "name": "Salesforce Certified Administrator",
    "provider": "Salesforce",
    "category": "CRM Platform",
    "level": "Administrator",
    "duration": "No expiration",
    "cost": 200,
    "image": "https://trailhead.salesforce.com/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fsfdc-dev%2Fimage%2Fupload%2Fc_fill%2Cf_auto%2Fh_240%2Cw_240%2Fv1%2FSalesforce_Default%2Fcertification_administrator_large.png&w=640&q=75",
    "description": "Configure and maintain Salesforce applications",
    "skills": ["User Management", "Data Management", "Security", "Automation", "Reports & Dashboards"],
    "prerequisites": ["6 months Salesforce experience (recommended)"],
    "examCode": "ADX-201",
    "popularity": 82,
    "averageSalary": 85000,
    "jobTitles": ["Salesforce Administrator", "CRM Administrator", "Business Analyst"],
    "officialUrl": "https://trailhead.salesforce.com/credentials/administrator"
  },
  {
    "id": 11,
    "name": "Docker Certified Associate",
    "provider": "Docker",
    "category": "Containerization",
    "level": "Associate",
    "duration": "2 years",
    "cost": 195,
    "image": "https://images.credly.com/size/340x340/images/8b8ed108-e77d-4396-ac59-2504583b9d54/cka_from_cncfsite__281_29.png",
    "description": "Docker platform skills and best practices",
    "skills": ["Docker Engine", "Images", "Containers", "Networking", "Security"],
    "prerequisites": ["6-12 months Docker experience"],
    "examCode": "DCA",
    "popularity": 70,
    "averageSalary": 110000,
    "jobTitles": ["DevOps Engineer", "Container Engineer", "Platform Engineer"],
    "officialUrl": "https://www.docker.com/certification"
  },
  {
    "id": 12,
    "name": "Terraform Associate",
    "provider": "HashiCorp",
    "category": "Infrastructure as Code",
    "level": "Associate",
    "duration": "2 years",
    "cost": 70,
    "image": "https://images.credly.com/size/340x340/images/99289602-861e-4929-8277-773e63a2fa6f/image.png",
    "description": "Infrastructure automation using Terraform",
    "skills": ["Infrastructure as Code", "Terraform Configuration", "State Management", "Modules", "Provisioning"],
    "prerequisites": ["Basic terminal skills and cloud experience"],
    "examCode": "003",
    "popularity": 75,
    "averageSalary": 120000,
    "jobTitles": ["Infrastructure Engineer", "DevOps Engineer", "Cloud Engineer"],
    "officialUrl": "https://www.hashicorp.com/certification/terraform-associate"
  }
]